###
POST http://localhost:8000/ai/v2/groups/recommendations/freeform
Content-Type: application/json

{
  "userId": 1,
  "requestText": "시끄럽지 않고 조용한 분위기의 모임이 좋을 것 같아요."
}


###
POST http://localhost:8000/ai/v2/groups/recommendations/freeform
Content-Type: application/json

{
  "userId": 2,
  "requestText": "몸을 많이 쓰는 활동적인 모임이 있을까요?"
}


###
POST http://localhost:8000/ai/v2/groups/recommendations/freeform
Content-Type: application/json

{
  "userId": 5,
  "requestText": "힐링하거나 스트레칭할 수 있는 모임 추천해주세요."
}

###
POST http://localhost:8000/ai/v2/groups/recommendations/freeform
Content-Type: application/json

{
  "userId": 3,
  "requestText": "개발이 처음이라 기초부터 차근차근 배울 수 있는 모임 있을까요?"
}

###
POST http://localhost:8000/ai/v2/groups/recommendations/freeform
Content-Type: application/json

{
  "userId": 1,
  "requestText": "책을 읽거나 글을 쓸 수 있는 조용한 모임이 좋을 것 같아요."
}
