services:
  zookeeper-local:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-local
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - nemo-net
    restart: unless-stopped
    volumes:
      - zookeeper-data:/data

  kafka-local:
    image: wurstmeister/kafka:latest
    container_name: kafka-local
    depends_on:
      - zookeeper-local
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.10.2.2:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "GROUP_EVENT:3:1,GROUP_RECOMMEND_QUESTION:3:1,GROUP_RECOMMEND:3:1,GROUP_GENERATE:3:1"
    networks:
      - nemo-net
    restart: unless-stopped
    volumes:
      - kafka-data:/kafka

  kafdrop-local:
    image: obsidiandynamics/kafdrop:3.30.0
    container_name: kafdrop-local
    depends_on:
      - kafka-local
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka-local:9092
      JVM_OPTS: -Xms32M -Xmx64M
      SERVER_SERVLET_CONTEXTPATH: /
    networks:
      - nemo-net
    restart: unless-stopped

networks:
  nemo-net:

volumes:
  kafka-data:
  zookeeper-data:
