###
POST http://grub-magical-totally.ngrok-free.app/ai/v2/chatbot/freeform
Content-Type: application/json

{
  "query": "시끄럽지 않고 조용한 분위기의 모임이 좋을 것 같아요.",
  "user_id": "u004"
}


###
POST http://grub-magical-totally.ngrok-free.app/ai/v2/chatbot/freeform
Content-Type: application/json

{
  "query": "몸을 많이 쓰는 활동적인 모임이 있을까요?",
  "user_id": "u002"
}


###
POST http://grub-magical-totally.ngrok-free.app/ai/v2/chatbot/freeform
Content-Type: application/json

{
  "query": "힐링하거나 스트레칭할 수 있는 모임 추천해주세요.",
  "user_id": "u005"
}

###
POST http://grub-magical-totally.ngrok-free.app/ai/v2/chatbot/freeform
Content-Type: application/json

{
  "query": "개발이 처음이라 기초부터 차근차근 배울 수 있는 모임 있을까요?",
  "user_id": "u003"
}

###
POST http://grub-magical-totally.ngrok-free.app/ai/v2/chatbot/freeform
Content-Type: application/json

{
  "query": "책을 읽거나 글을 쓸 수 있는 조용한 모임이 좋을 것 같아요.",
  "user_id": "u001"
}
