### 그룹 문서 저장
POST http://localhost:8000/ai/v2/vector/group
Content-Type: application/json

{
  "code": 201,
  "message": "그룹 문서 저장",
  "data": {
    "groupId": 123,
    "name": "SB 모임",
    "summary": "Spring boot를 개발할 수 있다.",
    "description": "안녕하세요 Spring boot를 학습하는 SB 모임입니다.",
    "category": "개발",
    "location": "판교",
    "maxUserCount": "50",
    "imageUrl": "image.jpg",
    "tags": ["Java", "비전공자 환영", "온라인스터디", "기초부터"],
    "plan": "매주 온라인으로 진행되는 Spring Boot 입문 스터디입니다."
  }
}

### 사용자 참여 문서 저장
POST http://localhost:8000/ai/v2/vector/user
Content-Type: application/json

{
  "code": 201,
  "message": "참여 정보 저장",
  "data": {
    "user_id": "user123",
    "group_id": "123"
  }
}

### 문서 전체 목록 조회
GET http://localhost:8000/ai/v2/vector/collection?collection=group-info&limit=10&offset=0

### 단건 조회
GET http://localhost:8000/ai/v2/vector/document?collection=group-info&id=group-123
