name: AI CI for v2-prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: '릴리즈 버전 태그 (예: v1.3.0)'
        required: true

jobs:
  build-and-deploy:
    name: Build & Deploy to AI Server
    runs-on: ubuntu-latest
    environment: prod

    env:
      REGION: asia-northeast3
      REPOSITORY: registry
      SERVICE: ai-prod
      ENVIRONMENT: prod
      DEPLOY_SCRIPT: ~/nemo/cloud/v2/scripts/deploy.sh

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set GCP Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID_AI }}

    - name: Set image tag and URI
      run: |
        TIME_TAG="${{ env.ENVIRONMENT }}-$(TZ=Asia/Seoul date +'%Y%m%d-%H%M')"
        echo "TIME_TAG=$TIME_TAG" >> $GITHUB_ENV

        VERSION_TAG="prod-${{ github.event.inputs.version }}"
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

        IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_AI }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}"
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build and Push Docker Image
      run: |+
        echo Checking pushed image: ${IMAGE_URI}:${TIME_TAG}
        echo Checking pushed image: ${IMAGE_URI}:${VERSION_TAG}
        echo Checking pushed image: ${IMAGE_URI}:${{ env.ENVIRONMENT }}-latest

        docker buildx build \
          --platform linux/amd64 \
          -t "${IMAGE_URI}:${TIME_TAG}" \
          -t "${IMAGE_URI}:${VERSION_TAG}" \
          -t "${IMAGE_URI}:${{ env.ENVIRONMENT }}-latest" \
          --push .
          
    - name: Deploy via Bastion to AI Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AI_HOST }}
        username: ${{ secrets.AI_USER }}
        key: ${{ secrets.AI_SSH_KEY }}

        proxy_host: ${{ secrets.BASTION_HOST }}
        proxy_username: ${{ secrets.BASTION_USER }}
        proxy_key: ${{ secrets.BASTION_SSH_KEY }}

        script: |
          bash ${{ env.DEPLOY_SCRIPT }} ${{ env.SERVICE }} ${{ env.ENVIRONMENT }}
